apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: v1 
kind: Pod
metadata:
  name: app-frontend
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-port": "80"
    "consul.hashicorp.com/connect-service-upstreams": "api:5000:eks"
  labels:
    app: bootcamp
spec:
  containers:
  - name: frontend
    image: codydearkland/app-frontend:latest
    ports:
    - containerPort: 80
  serviceAccountName: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bootcamp
  type: LoadBalancer
