apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
---
apiVersion: v1
kind: Pod
metadata:
  name: api
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-upstreams": "db:5432:gke"
    "vault.hashicorp.com/agent-inject": "true"
    "vault.hashicorp.com/agent-inject-secret-db": "secret/db"
    "vault.hashicorp.com/role": "api"
    "vault.hashicorp.com/agent-inject-template-db": |
          {{- with secret "secret/db" -}}
          host=localhost port=5432 dbname=posts user={{ .Data.username }} password={{ .Data.password  }}
          {{- end }}
spec:
  containers:
  - name: api
    image: codydearkland/apiv2:beta
    ports:
    - containerPort: 5000
  serviceAccountName: api
