apiVersion: v1
kind: ServiceAccount
metadata:
  name: db
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  containers:
  - name: db
    image: codydearkland/demodb:latest
    ports:
    - containerPort: 5432
  serviceAccountName: db
